提交刷包脚本
isrc-cas/PLCT-Toolbox pull request #4
Opened 2021-09-23 09:05 UTC by lvxiaoqian555

2021-09-23 14:20 UTC, lazyparser requested changes
Nice Try

总体而言体现出了思路清晰。

有机会可以实际跑一下。目测脚本中坑比较大。

2021-09-23 14:20 UTC, lazyparser commented on CI_script/ddTF.py
> +	print("Now dd image into "+tf+"...")
这里的 `tf` 是不是 `tfId` ？运行起来会 `undef error` 么

2021-09-23 14:20 UTC, lazyparser commented on CI_script/ddTF.py
> +	cmd="bzcat "+image+" | sudo dd of=/dev/"+tf+" bs=1M iflag=fullblock oflag=direct conv=fsync status=progress"
`bzcat` 最好是先解压缩出来。不然每次 `bzcat` 很浪费的。

`of` 用 字符串拼接方式很危险的哦。最好是要加入一个显示和确认的过程。

`iflag=fullblock oflag=direct conv=fsync` 可能是多余的？

2021-09-23 14:20 UTC, lazyparser commented on CI_script/ddTF.py
> +	cmd="sudo fdisk /dev/"+tf
这里和以下的过程，可以在dd的时候做，也可以在插入D1之后启动之后做。

自动化过程是OK的。不过用python来写可能不合适。要么是写成一个独立的 bash 脚本，要么是独立出来成一个 python 函数。

2021-09-23 14:20 UTC, lazyparser commented on CI_script/ddTF.py
> +	tfList=re.findall("Disk /dev/(sd[^a])",fdisk)
如果用户有两个盘，就崩了😁

最好是能够某种形式的检测或者交互的确认。

2021-09-23 14:20 UTC, lazyparser commented on CI_script/ddTF.py
> +		raise Exception("there is no TF connected to system")
一般性而言，如果没有U盘，就自然退出就行了，不用 raise

2021-09-23 14:20 UTC, lazyparser commented on CI_script/ddTF.py
> +	p.expect("password for .*:")
如果是免密码 sudo 或者连续两次 sudo （第二次 sudo 默认不用输入密码），那么这里会卡死么？

2021-09-23 14:21 UTC, lazyparser commented
提交 PR 的时候，后续慢慢的把 commit msg 和 PR title 和 PR msg 都尝试写完整一些，培养成习惯。

2021-09-24 04:10 UTC, closed without merging

2021-09-24 04:11 UTC, lvxiaoqian555 commented
要改进的地方很多，先撤回